Service: contentful-aleph

Stacks:
  Global:
    Tags:
      Name: $SERVICE-$STAGE
      Owner: ${USER}
      Contact: ${USER}@nd.edu
  Single:
    - Name: $SERVICE-$STAGE
      Template: root.yml
      Tags:
        Description: Contentful hook to populate aleph data
      Parameters:
        ServiceName: $SERVICE-$STAGE
        Stage: $STAGE
        TemplateBucket: $DEPLOY_BUCKET
        TemplateFolder: $DEPLOY_FOLDER

Artifacts:
  Templates:
    - root.yml
    - lambdas.yml
    - gateway.yml
  Zips:
    -
      Name: code
      Files:
        - ../lib/
        - ../handler.py
        - ../shared.py
        - ../sync.py

LambdaEnv:
  Global:
    KMSKey: alias/wse/kms/
  Single:
    - FunctionName: $SERVICE-$STAGE-hook
      Environment:
        -
          Name: ALEPH_URL
          Value: ${ALEPH_URL}
        -
          Name: OAUTH
          Value: ${OAUTH}
        -
          Name: CONTENTFUL_URL
          Value: ${CONTENTFUL_URL}

    - FunctionName: $SERVICE-$STAGE-sync
      Environment:
        -
          Name: ALEPH_URL
          Value: ${ALEPH_URL}
        -
          Name: OAUTH
          Value: ${OAUTH}
        -
          Name: CONTENTFUL_URL
          Value: ${CONTENTFUL_URL}
        -
          Name: CONTENTFUL_QUERY_URL
          Value: ${CONTENTFUL_QUERY_URL}
